server:
  port: 2000
spring:
  application:
    name: user-service-provider
  elasticsearch:
    jest:
      uris: http://47.98.174.58:9200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
feign:
  hystrix:
    enabled: true